import type {Customer,Appointment,Interaction} from "../types/crm";import {supabase} from "./supabase";
const key="honda-crm-demo";
const iso=(d:number)=>new Date(Date.now()+d*86400000).toISOString();
const demo:Customer[]=[["João da Silva","Honda CG 160","hot","lead_new"],["Maria Oliveira","Honda Biz","warm","follow_up"],["Carlos Santos","Honda CB 300F","hot","closing"],["Ana Costa","Honda PCX","warm","won"],["Pedro Lima","Honda NXR 160 Bros","hot","financing"],["Juliana Alves","Honda Sahara 300","warm","consortium"],["Rafael Souza","Honda XRE","cold","future_sale"],["Fernanda Rocha","Honda Pop 110i","cold","lost"],["Bruno Mendes","Honda ADV","hot","lead_new"],["Camila Reis","Honda CG 160","warm","follow_up"],["Lucas Martins","Honda PCX","hot","closing"],["Patricia Lima","Honda Biz","warm","financing"],["André Rocha","Honda XRE","cold","future_sale"],["Beatriz Melo","Honda CB 300F","hot","lead_new"],["Gustavo Alves","Honda Sahara 300","warm","follow_up"],["Renata Silva","Honda CG 160","hot","closing"],["Diego Ramos","Honda ADV","cold","lost"],["Larissa Nunes","Honda PCX","warm","won"],["Felipe Costa","Honda NXR 160 Bros","hot","consortium"],["Marcos Vieira","Honda Biz","warm","financing"]].map((x,i)=>({id:String(i+1),full_name:x[0]!,motorcycle_model:x[1]!,temperature:x[2] as any,pipeline_stage:x[3] as any,phone:"(99) 9 9999-000"+(i%10),whatsapp:"(99) 9 9999-000"+(i%10),lead_source:"WhatsApp",estimated_value:18000+i*750,available_down_payment:5000,desired_installment:650,has_trade_in:false,created_at:iso(-i),updated_at:iso(-i),next_follow_up_at:i<10?iso(0):null,last_contact_at:iso(-1)}));
export async function listCustomers(){if(supabase){const {data,error}=await supabase.from("customers").select("*,motorcycle_models(name)").order("created_at",{ascending:false});if(!error)return (data??[]).map((x:any)=>({...x,motorcycle_model:x.motorcycle_models?.name??x.motorcycle_model}));}const saved=localStorage.getItem(key);return saved?JSON.parse(saved):demo;}
export async function getCustomer(id:string){return (await listCustomers()).find((x:Customer)=>x.id===id)??null;}
export async function saveCustomer(input:Partial<Customer>){const customer={...input,id:input.id??crypto.randomUUID(),full_name:input.full_name!,pipeline_stage:input.pipeline_stage??"lead_new",temperature:input.temperature??"warm",has_trade_in:Boolean(input.has_trade_in),created_at:input.created_at??new Date().toISOString(),updated_at:new Date().toISOString()} as Customer;if(supabase){const {data,error}=await supabase.from("customers").upsert(customer).select().single();if(error)throw error;return data as Customer}const all=await listCustomers();localStorage.setItem(key,JSON.stringify([customer,...all.filter((x:Customer)=>x.id!==customer.id)]));return customer;}
export async function moveCustomer(id:string,stage:Customer["pipeline_stage"]){const c=await getCustomer(id);if(!c)throw new Error("Cliente não encontrado");await saveCustomer({...c,pipeline_stage:stage});if(supabase)await supabase.from("sales_pipeline_history").insert({customer_id:id,from_stage:c.pipeline_stage,to_stage:stage});}
export async function listAppointments():Promise<Appointment[]>{if(supabase){const {data}=await supabase.from("appointments").select("*,customers(full_name,motorcycle_model)").order("scheduled_at");return (data??[]).map((x:any)=>({...x,customer_name:x.customers?.full_name,motorcycle_model:x.customers?.motorcycle_model}));}return JSON.parse(localStorage.getItem("honda-crm-appts")??"[]");}
export async function saveAppointment(a:Omit<Appointment,"id">){const item={...a,id:crypto.randomUUID()};if(supabase){const {data,error}=await supabase.from("appointments").insert(a).select().single();if(error)throw error;return data as Appointment}const all=await listAppointments();localStorage.setItem("honda-crm-appts",JSON.stringify([...all,item]));return item;}
export async function listInteractions(id:string):Promise<Interaction[]>{if(supabase){const {data}=await supabase.from("customer_interactions").select("*").eq("customer_id",id).order("created_at",{ascending:false});return data??[]}return JSON.parse(localStorage.getItem("honda-crm-int-"+id)??"[]");}
export async function saveInteraction(i:Omit<Interaction,"id"|"created_at">){const item={...i,id:crypto.randomUUID(),created_at:new Date().toISOString()};if(supabase){const {data,error}=await supabase.from("customer_interactions").insert(i).select().single();if(error)throw error;await supabase.from("customers").update({last_contact_at:item.created_at}).eq("id",i.customer_id);return data as Interaction}const all=await listInteractions(i.customer_id);localStorage.setItem("honda-crm-int-"+i.customer_id,JSON.stringify([item,...all]));return item;}