import {supabase} from "./supabase";import {listCustomers} from "./data";import {listProposals,listFinancing,listConsortium,listFutureSales,listLost,listActivities,listSales} from "./commercial";
export type Period={start:Date;end:Date;label:string};export type Filters={period:Period;seller?:string;model?:string;stage?:string;source?:string;payment?:string};
export function periodOf(kind:string):Period{const n=new Date(),y=n.getFullYear(),m=n.getMonth();let s=new Date(y,m,1),e=new Date(y,m+1,1);if(kind==="today"){s=new Date(y,m,n.getDate());e=new Date(y,m,n.getDate()+1)}else if(kind==="week"){const d=n.getDay();s=new Date(y,m,n.getDate()-d);e=new Date(s);e.setDate(s.getDate()+7)}else if(kind==="prev_month"){s=new Date(y,m-1,1);e=new Date(y,m,1)}else if(kind==="quarter"){const q=Math.floor(m/3);s=new Date(y,q*3,1);e=new Date(y,q*3+3,1)}else if(kind==="year"){s=new Date(y,0,1);e=new Date(y+1,0,1)}return {start:s,end:e,label:kind}}
export function inPeriod(d:string|undefined,p:Period){return !!d&&new Date(d)>=p.start&&new Date(d)<p.end}export function pct(a:number,b:number){return b?Math.round(a/b*1000)/10:0}export function money(n:number){return (n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0})}
export async function loadAnalytics(){const [customers,proposals,financing,consortium,future,lost,activities,sales]=await Promise.all([listCustomers(),listProposals(),listFinancing(),listConsortium(),listFutureSales(),listLost(),listActivities(),listSales()]);return {customers,proposals,financing,consortium,future,lost,activities,sales}}
export async function listGoals(){if(!supabase)return JSON.parse(localStorage.getItem("honda-crm-goals")||"[]");const {data,error}=await supabase.from("sales_goals").select("*").order("start_date",{ascending:false});if(error)throw error;return data??[]}
export async function saveGoal(g:any){if(!supabase){const all=await listGoals(),x={...g,id:g.id??crypto.randomUUID(),created_at:g.created_at??new Date().toISOString(),updated_at:new Date().toISOString()};localStorage.setItem("honda-crm-goals",JSON.stringify([x,...all.filter((z:any)=>z.id!==x.id)]));return x}const {data,error}=await supabase.from("sales_goals").upsert(g).select().single();if(error)throw error;return data}
export async function listProfiles(){if(!supabase)return JSON.parse(localStorage.getItem("honda-crm-profiles")||"[]");const {data,error}=await supabase.from("profiles").select("*").order("full_name");if(error)throw error;return data??[]}
export async function saveProfile(p:any){if(!supabase){const all=await listProfiles(),x={...p,id:p.id??crypto.randomUUID(),user_id:p.user_id??crypto.randomUUID(),created_at:p.created_at??new Date().toISOString(),updated_at:new Date().toISOString()};localStorage.setItem("honda-crm-profiles",JSON.stringify([x,...all.filter((z:any)=>z.id!==x.id)]));return x}const {data,error}=await supabase.from("profiles").upsert(p).select().single();if(error)throw error;return data}
export async function listAudits(filters?:any){if(!supabase)return JSON.parse(localStorage.getItem("honda-crm-audit")||"[]");let q=supabase.from("audit_logs").select("*,profiles(full_name)").order("created_at",{ascending:false}).limit(500);if(filters?.user_id)q=q.eq("user_id",filters.user_id);if(filters?.entity_type)q=q.eq("entity_type",filters.entity_type);if(filters?.action)q=q.eq("action",filters.action);const {data,error}=await q;if(error)throw error;return data??[]}
export async function audit(action:string,entity_type:string,entity_id?:string,old_values?:any,new_values?:any){if(!supabase){const all=JSON.parse(localStorage.getItem("honda-crm-audit")||"[]");all.unshift({id:crypto.randomUUID(),action,entity_type,entity_id,old_values,new_values,created_at:new Date().toISOString()});localStorage.setItem("honda-crm-audit",JSON.stringify(all));return}await supabase.from("audit_logs").insert({action,entity_type,entity_id,old_values,new_values})}
export function exportCsv(filename:string,rows:Record<string,unknown>[]){if(!rows.length)return false;const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const esc=(v:unknown)=>'"'+String(v??"").replaceAll('"','""')+'"';const csv=[keys.map(esc).join(";"),...rows.map(r=>keys.map(k=>esc(r[k])).join(";"))].join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href);return true}
