import {supabase} from "./supabase";
export type Role="admin"|"manager"|"seller";
export const ROLE_LABELS:{[k in Role]:string}={admin:"Administrador",manager:"Gerente",seller:"Vendedor"};
export const PERMISSIONS=["dashboard.view","customers.view","customers.create","customers.edit","customers.delete","pipeline.view","pipeline.move","appointments.view","appointments.create","appointments.edit","proposals.view","proposals.create","proposals.edit","financing.view","financing.create","financing.edit","consortium.view","consortium.create","consortium.edit","reports.view","reports.export","team.view","team.manage","goals.view","goals.manage","users.view","users.manage","settings.manage","audit.view"] as const;
const ROLE_PERMS:Record<Role,readonly string[]>={admin:PERMISSIONS,manager:["dashboard.view","customers.view","customers.create","customers.edit","pipeline.view","pipeline.move","appointments.view","appointments.create","appointments.edit","proposals.view","proposals.create","proposals.edit","financing.view","financing.create","financing.edit","consortium.view","consortium.create","consortium.edit","reports.view","reports.export","team.view","team.manage","goals.view","goals.manage"],seller:["dashboard.view","customers.view","customers.create","customers.edit","pipeline.view","pipeline.move","appointments.view","appointments.create","appointments.edit","proposals.view","proposals.create","proposals.edit","financing.view","financing.create","financing.edit","consortium.view","consortium.create","consortium.edit"]};
export async function currentProfile(){if(typeof window==="undefined")return null;let role=(localStorage.getItem("honda-crm-role")||"seller") as Role;if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from("profiles").select("*").eq("user_id",user.id).maybeSingle();if(data){role=data.role as Role;localStorage.setItem("honda-crm-role",role);return data}}}return {id:"demo",user_id:"demo",full_name:"Usuário",email:"",role} as any}
export async function hasPermission(permission:string){const p=await currentProfile();return !!p&&ROLE_PERMS[p.role as Role]?.includes(permission)}
export async function requirePermission(permission:string){if(typeof window==="undefined")return;const ok=localStorage.getItem("honda-crm-auth")&&await hasPermission(permission);if(!ok)location.href="/dashboard"}
export async function requireRole(...roles:Role[]){if(typeof window==="undefined")return;const p=await currentProfile();if(!localStorage.getItem("honda-crm-auth")||!p||!roles.includes(p.role as Role))location.href="/dashboard";return p}
export function can(role:Role,permission:string){return ROLE_PERMS[role]?.includes(permission)??false}
