/* eslint-disable */\n// @ts-nocheck\nimport {Route as rootRouteImport} from './routes/__root'\nimport {Route as IndexRouteImport} from './routes/index'\nimport {Route as LoginRouteImport} from './routes/login'\nimport {Route as DashboardRouteImport} from './routes/dashboard'\nimport {Route as ClientesRouteImport} from './routes/clientes'\nimport {Route as ClientesNovoRouteImport} from './routes/clientes.novo'\nimport {Route as ClienteIdRouteImport} from './routes/clientes.$id'\nimport {Route as FunilRouteImport} from './routes/funil'\nimport {Route as AgendaRouteImport} from './routes/agenda'\nconst IndexRoute=IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const LoginRoute=LoginRouteImport.update({id:'/login',path:'/login',getParentRoute:()=>rootRouteImport} as any)
const DashboardRoute=DashboardRouteImport.update({id:'/dashboard',path:'/dashboard',getParentRoute:()=>rootRouteImport} as any)
const ClientesRoute=ClientesRouteImport.update({id:'/clientes',path:'/clientes',getParentRoute:()=>rootRouteImport} as any)
const ClientesNovoRoute=ClientesNovoRouteImport.update({id:'/clientes/novo',path:'/clientes/novo',getParentRoute:()=>rootRouteImport} as any)
const ClienteIdRoute=ClienteIdRouteImport.update({id:'/clientes/$id',path:'/clientes/$id',getParentRoute:()=>rootRouteImport} as any)
const FunilRoute=FunilRouteImport.update({id:'/funil',path:'/funil',getParentRoute:()=>rootRouteImport} as any)
const AgendaRoute=AgendaRouteImport.update({id:'/agenda',path:'/agenda',getParentRoute:()=>rootRouteImport} as any)
export interface FileRoutesByFullPath{'/':typeof IndexRoute;'/login':typeof LoginRoute;'/dashboard':typeof DashboardRoute;'/clientes':typeof ClientesRoute;'/clientes/novo':typeof ClientesNovoRoute;'/clientes/$id':typeof ClienteIdRoute;'/funil':typeof FunilRoute;'/agenda':typeof AgendaRoute}
export interface FileRoutesByTo{ '/':typeof IndexRoute;'/login':typeof LoginRoute;'/dashboard':typeof DashboardRoute;'/clientes':typeof ClientesRoute;'/clientes/novo':typeof ClientesNovoRoute;'/clientes/$id':typeof ClienteIdRoute;'/funil':typeof FunilRoute;'/agenda':typeof AgendaRoute}
export interface FileRoutesById{'__root__':typeof rootRouteImport;'/':typeof IndexRoute;'/login':typeof LoginRoute;'/dashboard':typeof DashboardRoute;'/clientes':typeof ClientesRoute;'/clientes/novo':typeof ClientesNovoRoute;'/clientes/$id':typeof ClienteIdRoute;'/funil':typeof FunilRoute;'/agenda':typeof AgendaRoute}
export interface FileRouteTypes{fileRoutesByFullPath:FileRoutesByFullPath;fullPaths:'/'|'/login'|'/dashboard'|'/clientes'|'/clientes/novo'|'/clientes/$id'|'/funil'|'/agenda';fileRoutesByTo:FileRoutesByTo;to:'/'|'/login'|'/dashboard'|'/clientes'|'/clientes/novo'|'/clientes/$id'|'/funil'|'/agenda';id:'__root__'|'/'|'/login'|'/dashboard'|'/clientes'|'/clientes/novo'|'/clientes/$id'|'/funil'|'/agenda';fileRoutesById:FileRoutesById}
declare module '@tanstack/react-router'{interface FileRoutesByPath{'/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport};'/login':{id:'/login';path:'/login';fullPath:'/login';preLoaderRoute:typeof LoginRouteImport;parentRoute:typeof rootRouteImport};'/dashboard':{id:'/dashboard';path:'/dashboard';fullPath:'/dashboard';preLoaderRoute:typeof DashboardRouteImport;parentRoute:typeof rootRouteImport};'/clientes':{id:'/clientes';path:'/clientes';fullPath:'/clientes';preLoaderRoute:typeof ClientesRouteImport;parentRoute:typeof rootRouteImport};'/clientes/novo':{id:'/clientes/novo';path:'/clientes/novo';fullPath:'/clientes/novo';preLoaderRoute:typeof ClientesNovoRouteImport;parentRoute:typeof rootRouteImport};'/clientes/$id':{id:'/clientes/$id';path:'/clientes/$id';fullPath:'/clientes/$id';preLoaderRoute:typeof ClienteIdRouteImport;parentRoute:typeof rootRouteImport};'/funil':{id:'/funil';path:'/funil';fullPath:'/funil';preLoaderRoute:typeof FunilRouteImport;parentRoute:typeof rootRouteImport};'/agenda':{id:'/agenda';path:'/agenda';fullPath:'/agenda';preLoaderRoute:typeof AgendaRouteImport;parentRoute:typeof rootRouteImport}}}
const rootRouteChildren={IndexRoute,LoginRoute,DashboardRoute,ClientesRoute,ClientesNovoRoute,ClienteIdRoute,FunilRoute,AgendaRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()