/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConsorciosRouteImport } from './routes/consorcios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as DesistenciasRouteImport } from './routes/desistencias'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as FinanciamentosRouteImport } from './routes/financiamentos'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VendasFuturasRouteImport } from './routes/vendas-futuras'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as ConfiguracoesModelosRouteImport } from './routes/configuracoes.modelos'
import { Route as ConsorciosNovoRouteImport } from './routes/consorcios.novo'
import { Route as DesistenciasNovaRouteImport } from './routes/desistencias.nova'
import { Route as EquipeIdRouteImport } from './routes/equipe.$id'
import { Route as FinanciamentosNovaRouteImport } from './routes/financiamentos.nova'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as PropostasNovaRouteImport } from './routes/propostas.nova'
import { Route as VendasFuturasNovaRouteImport } from './routes/vendas-futuras.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsorciosRoute = ConsorciosRouteImport.update({
  id: '/consorcios',
  path: '/consorcios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const DesistenciasRoute = DesistenciasRouteImport.update({
  id: '/desistencias',
  path: '/desistencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosRoute = FinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasFuturasRoute = VendasFuturasRouteImport.update({
  id: '/vendas-futuras',
  path: '/vendas-futuras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClientesRoute,
} as any)
const ConfiguracoesModelosRoute = ConfiguracoesModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConsorciosNovoRoute = ConsorciosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ConsorciosRoute,
} as any)
const DesistenciasNovaRoute = DesistenciasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => DesistenciasRoute,
} as any)
const EquipeIdRoute = EquipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipeRoute,
} as any)
const FinanciamentosNovaRoute = FinanciamentosNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => FinanciamentosRoute,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropostasRoute,
} as any)
const PropostasNovaRoute = PropostasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => PropostasRoute,
} as any)
const VendasFuturasNovaRoute = VendasFuturasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => VendasFuturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/consorcios': typeof ConsorciosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/desempenho': typeof DesempenhoRoute
  '/desistencias': typeof DesistenciasRouteWithChildren
  '/equipe': typeof EquipeRouteWithChildren
  '/financiamentos': typeof FinanciamentosRouteWithChildren
  '/funil': typeof FunilRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas-futuras': typeof VendasFuturasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/modelos': typeof ConfiguracoesModelosRoute
  '/consorcios/novo': typeof ConsorciosNovoRoute
  '/desistencias/nova': typeof DesistenciasNovaRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/financiamentos/nova': typeof FinanciamentosNovaRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/vendas-futuras/nova': typeof VendasFuturasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/consorcios': typeof ConsorciosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/desempenho': typeof DesempenhoRoute
  '/desistencias': typeof DesistenciasRouteWithChildren
  '/equipe': typeof EquipeRouteWithChildren
  '/financiamentos': typeof FinanciamentosRouteWithChildren
  '/funil': typeof FunilRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas-futuras': typeof VendasFuturasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/modelos': typeof ConfiguracoesModelosRoute
  '/consorcios/novo': typeof ConsorciosNovoRoute
  '/desistencias/nova': typeof DesistenciasNovaRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/financiamentos/nova': typeof FinanciamentosNovaRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/vendas-futuras/nova': typeof VendasFuturasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auditoria': typeof AuditoriaRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/consorcios': typeof ConsorciosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/desempenho': typeof DesempenhoRoute
  '/desistencias': typeof DesistenciasRouteWithChildren
  '/equipe': typeof EquipeRouteWithChildren
  '/financiamentos': typeof FinanciamentosRouteWithChildren
  '/funil': typeof FunilRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas-futuras': typeof VendasFuturasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/modelos': typeof ConfiguracoesModelosRoute
  '/consorcios/novo': typeof ConsorciosNovoRoute
  '/desistencias/nova': typeof DesistenciasNovaRoute
  '/equipe/$id': typeof EquipeIdRoute
  '/financiamentos/nova': typeof FinanciamentosNovaRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/vendas-futuras/nova': typeof VendasFuturasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auditoria'
    | '/clientes'
    | '/configuracoes'
    | '/consorcios'
    | '/dashboard'
    | '/desempenho'
    | '/desistencias'
    | '/equipe'
    | '/financiamentos'
    | '/funil'
    | '/gestao'
    | '/login'
    | '/metas'
    | '/propostas'
    | '/relatorios'
    | '/usuarios'
    | '/vendas-futuras'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/modelos'
    | '/consorcios/novo'
    | '/desistencias/nova'
    | '/equipe/$id'
    | '/financiamentos/nova'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/vendas-futuras/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auditoria'
    | '/clientes'
    | '/configuracoes'
    | '/consorcios'
    | '/dashboard'
    | '/desempenho'
    | '/desistencias'
    | '/equipe'
    | '/financiamentos'
    | '/funil'
    | '/gestao'
    | '/login'
    | '/metas'
    | '/propostas'
    | '/relatorios'
    | '/usuarios'
    | '/vendas-futuras'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/modelos'
    | '/consorcios/novo'
    | '/desistencias/nova'
    | '/equipe/$id'
    | '/financiamentos/nova'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/vendas-futuras/nova'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auditoria'
    | '/clientes'
    | '/configuracoes'
    | '/consorcios'
    | '/dashboard'
    | '/desempenho'
    | '/desistencias'
    | '/equipe'
    | '/financiamentos'
    | '/funil'
    | '/gestao'
    | '/login'
    | '/metas'
    | '/propostas'
    | '/relatorios'
    | '/usuarios'
    | '/vendas-futuras'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/modelos'
    | '/consorcios/novo'
    | '/desistencias/nova'
    | '/equipe/$id'
    | '/financiamentos/nova'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/vendas-futuras/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ConsorciosRoute: typeof ConsorciosRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DesempenhoRoute: typeof DesempenhoRoute
  DesistenciasRoute: typeof DesistenciasRouteWithChildren
  EquipeRoute: typeof EquipeRouteWithChildren
  FinanciamentosRoute: typeof FinanciamentosRouteWithChildren
  FunilRoute: typeof FunilRoute
  GestaoRoute: typeof GestaoRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  PropostasRoute: typeof PropostasRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
  VendasFuturasRoute: typeof VendasFuturasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consorcios': {
      id: '/consorcios'
      path: '/consorcios'
      fullPath: '/consorcios'
      preLoaderRoute: typeof ConsorciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desistencias': {
      id: '/desistencias'
      path: '/desistencias'
      fullPath: '/desistencias'
      preLoaderRoute: typeof DesistenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas-futuras': {
      id: '/vendas-futuras'
      path: '/vendas-futuras'
      fullPath: '/vendas-futuras'
      preLoaderRoute: typeof VendasFuturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/configuracoes/modelos': {
      id: '/configuracoes/modelos'
      path: '/modelos'
      fullPath: '/configuracoes/modelos'
      preLoaderRoute: typeof ConfiguracoesModelosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/consorcios/novo': {
      id: '/consorcios/novo'
      path: '/novo'
      fullPath: '/consorcios/novo'
      preLoaderRoute: typeof ConsorciosNovoRouteImport
      parentRoute: typeof ConsorciosRoute
    }
    '/desistencias/nova': {
      id: '/desistencias/nova'
      path: '/nova'
      fullPath: '/desistencias/nova'
      preLoaderRoute: typeof DesistenciasNovaRouteImport
      parentRoute: typeof DesistenciasRoute
    }
    '/equipe/$id': {
      id: '/equipe/$id'
      path: '/$id'
      fullPath: '/equipe/$id'
      preLoaderRoute: typeof EquipeIdRouteImport
      parentRoute: typeof EquipeRoute
    }
    '/financiamentos/nova': {
      id: '/financiamentos/nova'
      path: '/nova'
      fullPath: '/financiamentos/nova'
      preLoaderRoute: typeof FinanciamentosNovaRouteImport
      parentRoute: typeof FinanciamentosRoute
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/propostas/nova': {
      id: '/propostas/nova'
      path: '/nova'
      fullPath: '/propostas/nova'
      preLoaderRoute: typeof PropostasNovaRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/vendas-futuras/nova': {
      id: '/vendas-futuras/nova'
      path: '/nova'
      fullPath: '/vendas-futuras/nova'
      preLoaderRoute: typeof VendasFuturasNovaRouteImport
      parentRoute: typeof VendasFuturasRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
  ClientesNovoRoute: ClientesNovoRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesModelosRoute: typeof ConfiguracoesModelosRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesModelosRoute: ConfiguracoesModelosRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface ConsorciosRouteChildren {
  ConsorciosNovoRoute: typeof ConsorciosNovoRoute
}

const ConsorciosRouteChildren: ConsorciosRouteChildren = {
  ConsorciosNovoRoute: ConsorciosNovoRoute,
}

const ConsorciosRouteWithChildren = ConsorciosRoute._addFileChildren(
  ConsorciosRouteChildren,
)

interface DesistenciasRouteChildren {
  DesistenciasNovaRoute: typeof DesistenciasNovaRoute
}

const DesistenciasRouteChildren: DesistenciasRouteChildren = {
  DesistenciasNovaRoute: DesistenciasNovaRoute,
}

const DesistenciasRouteWithChildren = DesistenciasRoute._addFileChildren(
  DesistenciasRouteChildren,
)

interface EquipeRouteChildren {
  EquipeIdRoute: typeof EquipeIdRoute
}

const EquipeRouteChildren: EquipeRouteChildren = {
  EquipeIdRoute: EquipeIdRoute,
}

const EquipeRouteWithChildren =
  EquipeRoute._addFileChildren(EquipeRouteChildren)

interface FinanciamentosRouteChildren {
  FinanciamentosNovaRoute: typeof FinanciamentosNovaRoute
}

const FinanciamentosRouteChildren: FinanciamentosRouteChildren = {
  FinanciamentosNovaRoute: FinanciamentosNovaRoute,
}

const FinanciamentosRouteWithChildren = FinanciamentosRoute._addFileChildren(
  FinanciamentosRouteChildren,
)

interface PropostasRouteChildren {
  PropostasIdRoute: typeof PropostasIdRoute
  PropostasNovaRoute: typeof PropostasNovaRoute
}

const PropostasRouteChildren: PropostasRouteChildren = {
  PropostasIdRoute: PropostasIdRoute,
  PropostasNovaRoute: PropostasNovaRoute,
}

const PropostasRouteWithChildren = PropostasRoute._addFileChildren(
  PropostasRouteChildren,
)

interface VendasFuturasRouteChildren {
  VendasFuturasNovaRoute: typeof VendasFuturasNovaRoute
}

const VendasFuturasRouteChildren: VendasFuturasRouteChildren = {
  VendasFuturasNovaRoute: VendasFuturasNovaRoute,
}

const VendasFuturasRouteWithChildren = VendasFuturasRoute._addFileChildren(
  VendasFuturasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuditoriaRoute: AuditoriaRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ConsorciosRoute: ConsorciosRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DesempenhoRoute: DesempenhoRoute,
  DesistenciasRoute: DesistenciasRouteWithChildren,
  EquipeRoute: EquipeRouteWithChildren,
  FinanciamentosRoute: FinanciamentosRouteWithChildren,
  FunilRoute: FunilRoute,
  GestaoRoute: GestaoRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  PropostasRoute: PropostasRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
  VendasFuturasRoute: VendasFuturasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
